(source melpa)
(source "tromey" "http://tromey.com/elpa/")

(depends-on "cask")
(depends-on "dash")
(depends-on "drag-stuff")
(depends-on "epl")
(depends-on "expand-region")
(depends-on "f")
(depends-on "git-commit-mode")
(depends-on "git-rebase-mode")
(depends-on "magit")
(depends-on "multiple-cursors")
(depends-on "pallet")
(depends-on "pkg-info")
(depends-on "popwin")
(depends-on "php-mode")
(depends-on "projectile")
(depends-on "s")
(depends-on "sql-indent")
(depends-on "smartparens")
(depends-on "smex")
(depends-on "solarized-theme")
(depends-on "wrap-region")
(depends-on "yasnippet")